version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\cmake-init
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64

matrix:
  fast_finish: true

environment:
  matrix:
    - GENERATOR: "Visual Studio 15"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15"
      CONFIG: Release

    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release

build_script:
	- cmake .. -G "%GENERATOR%" -B build
	- cmake --build build --config "%CONFIG%"

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - examples/
    - docs/
